# Generated by Django 5.0.3 on 2024-03-24 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Todo_uploud_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='To_uploud_userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
