# Generated by Django 5.0.3 on 2024-03-24 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_alter_todomodel_user_alter_todomodel_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouserprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Todo_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
