# Generated by Django 5.0.3 on 2024-03-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0003_alter_todouserprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='clue',
            field=models.CharField(default=1, max_length=50, verbose_name='Подсказка'),
            preserve_default=False,
        ),
    ]
