# Generated by Django 5.0.3 on 2024-03-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0004_todomodel_clue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='anonim_to_do',
        ),
    ]
