# Generated by Django 5.0.3 on 2024-03-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0005_remove_todomodel_anonim_to_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
