# Generated by Django 5.0.3 on 2024-03-25 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0006_todomodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='reminder_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время напоминания'),
        ),
    ]
